version: "2"
services:
    webdev:
          build:
              context: . 
              dockerfile: Dockerfile
          ports:
              - "80:80"
          volumes:
              - ./src:/src
          tty: true
    postgres:
          build:
              context: postgres
          image: postgres
          ports:
              - "5432:5432"